In [2]:
import numpy as np
ages=np.array([12,45,62,78,19])

In [3]:
ages

array([12, 45, 62, 78, 19])

In [4]:
import numpy as np
marks=np.array([98,97,48,67,86,85])

In [5]:
marks

array([98, 97, 48, 67, 86, 85])

In [20]:
import numpy as np

marks = np.array([85, 90, 78, 92, 88, 76], dtype="float")

print("Marks:", marks)
print("Data type:", marks.dtype)

Marks: [85. 90. 78. 92. 88. 76.]
Data type: float64


In [3]:
import numpy as np
arr=np.array([1,2,3,4,5,6],dtype=float)
print(arr)
print(type(arr))
print(arr.dtype)

[1. 2. 3. 4. 5. 6.]
<class 'numpy.ndarray'>
float64


In [6]:
arr=np.array([10,9,8,7,6,5],dtype="float32")
print(arr)
print(type(arr))
print(arr.dtype)

[10.  9.  8.  7.  6.  5.]
<class 'numpy.ndarray'>
float32


In [7]:
arr=np.array([1.2,3.4,5.6,8.9,12.4,16.7],dtype="int")
print(arr)


[ 1  3  5  8 12 16]


In [10]:
arr=np.array([1,2,3,4,5,6,7],dtype=str)
print(arr)
print(type(arr))
print(arr.dtype)

['1' '2' '3' '4' '5' '6' '7']
<class 'numpy.ndarray'>
<U1


In [15]:
arr=np.array([[1,2,3,4,5,6],[10,9,8,7,6,5]])
print(type(arr))
print(arr.dtype)
print(np.ndim(arr))

print(arr[0][3])
print(arr[1][5])

<class 'numpy.ndarray'>
int64
2
4
5


In [30]:
arr=np.array([[10,20,30,40],[50,60,70,80]])
print(arr[0:2,1:3])

[[20 30]
 [60 70]]


In [6]:
# let us create 3D array
import numpy as np
arr = np.array([
    [
        [10, 20, 30],
        [40, 50, 60]
    ],
    [
        [70, 80, 90],
        [100, 110, 120]
    ]
])
print(arr)
print(arr[0][1][2])
print(arr[1][0][1])
print(arr[1][1][2])

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]
60
80
120


In [7]:
arr=np.array([101,20,-30,40,50])
print(arr)
print(np.argmin(arr))
print(np.argmax(arr))
print(np.argsort(arr))

[101  20 -30  40  50]
2
0
[2 1 3 4 0]


In [13]:
# zeros()
arr=np.zeros((3,4),dtype=int)
print(arr)

arr=np.zeros((3,4),dtype=float)
print(arr)

arr=np.zeros((3,4),dtype="str")
print(arr)

arr=np.zeros((2,4))
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
# identity()

arr=np.identity(4,dtype=float)
print(arr)

arr=np.identity(3,dtype=float)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
arr=np.eye(5,5,2,dtype=float)
print(arr)

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
print(np.random.rand(3,4))

[[0.91343186 0.64530019 0.4142358  0.73576613]
 [0.84385175 0.90487243 0.17802164 0.94516202]
 [0.97243615 0.76341117 0.91840575 0.78747065]]


In [27]:
print(np.random.randint(10,50,size=(3,4)))

[[16 33 18 47]
 [21 10 12 41]
 [48 26 23 40]]


In [28]:
print(np.random.randn(3,4))

[[ 0.31486437  0.77719034  0.68652306 -0.65620059]
 [-0.24299124  0.82584907  0.14275137 -0.73744026]
 [ 1.4625729  -2.42291442 -0.49837582 -0.08292347]]


In [30]:
arr=np.array([10,20,30,40,50])
print(np.random.choice(arr,size=2,replace=False))

[30 50]


In [32]:
arr=np.arange(5)
print(arr)

[0 1 2 3 4]


In [33]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
np.arange(12).reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [4]:
import numpy as np
arr=np.arange(16).reshape(4,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [5]:
arr+5

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [6]:
arr-3

array([[-3, -2, -1,  0],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
arr*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [12]:
arr1=np.arange(15).reshape(5,3)
arr2=np.arange(5).reshape(5,1)
print(arr1)
print(arr2)
print(arr1+arr2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]
 [16 17 18]]


In [15]:
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8],[9,10],[11,12]])
C=np.dot(A,B)
print(C)

D=A@B
print(D)

E=np.matmul(A,B)
print(E)


[[ 58  64]
 [139 154]]
[[ 58  64]
 [139 154]]
[[ 58  64]
 [139 154]]


In [16]:
a=np.array([
    [5,2,3],
    [2,8,6],
    [6,3,2]
])
b=np.array([4,10,18])
np.linalg.solve(a,b)

array([ 2.41666667,  5.33333333, -6.25      ])

In [17]:
A=np.array([
    [1,2],
    [3,4]
])
print(A)
print(np.linalg.det(A))

[[1 2]
 [3 4]]
-2.0000000000000004
