In [1]:
import numpy as np

In [2]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [3]:
arr1

array([[2, 2, 2],
       [2, 2, 1],
       [2, 2, 1]], dtype=int32)

In [4]:
arr2

array([[1, 1, 1],
       [2, 1, 2],
       [1, 2, 1]], dtype=int32)

In [5]:
arr1.flatten() # Return a copy of the array collapsed into one dimension.

array([2, 2, 2, 2, 2, 1, 2, 2, 1], dtype=int32)

In [6]:
# expand dimension
arr=np.array([1,2,3,4])

In [7]:
arr

array([1, 2, 3, 4])

In [8]:
arr.ndim

1

In [9]:
np.expand_dims(arr,axis=0) # increase the dimension by 1 in the provided axis,0 means rows(x-axis) and 1 means column wise (y-axis). 

array([[1, 2, 3, 4]])

In [10]:
np.expand_dims(arr,axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [11]:
np.expand_dims(arr,axis=1).ndim

2

In [12]:
arr=np.zeros((3,4))

In [13]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.expand_dims(arr,axis=0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [15]:
np.expand_dims(arr,axis=0).ndim

3

In [16]:
np.expand_dims(arr,axis=1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [17]:
np.expand_dims(arr,axis=0).ndim

3

In [18]:
a=np.array([[1],[2],[3]])

In [19]:
a

array([[1],
       [2],
       [3]])

In [20]:
a.ndim

2

In [ ]:
# squeezing the dimension by 1 dimension
np.squeeze(a) # Remove axes of length one from 'a'

array([1, 2, 3])

In [22]:
a

array([[1],
       [2],
       [3]])

In [23]:
np.repeat(a,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [24]:
arr1

array([[2, 2, 2],
       [2, 2, 1],
       [2, 2, 1]], dtype=int32)

In [25]:
np.repeat(arr1,2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1], dtype=int32)

In [26]:
np.repeat(arr1,2,axis=0)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 1],
       [2, 2, 1],
       [2, 2, 1],
       [2, 2, 1]], dtype=int32)

In [27]:
np.repeat(arr2,3,axis=0)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 1, 2],
       [2, 1, 2],
       [2, 1, 2],
       [1, 2, 1],
       [1, 2, 1],
       [1, 2, 1]], dtype=int32)

In [28]:
np.repeat(arr2,3,axis=1)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2, 1, 1, 1]], dtype=int32)

In [29]:
a

array([[1],
       [2],
       [3]])

In [ ]:
np.roll(a,-1) # shift places

array([[2],
       [3],
       [1]])

In [31]:
np.roll(a,-2)

array([[3],
       [1],
       [2]])

In [ ]:
c=np.array([])

In [32]:
c=np.array([[1,2],[3,4],[5,6],[7,8]])

In [33]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [34]:
np.roll(c,-1)

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 1]])

In [35]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [36]:
np.roll(c,2)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [37]:
np.roll(c,2,axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [38]:
arr1

array([[2, 2, 2],
       [2, 2, 1],
       [2, 2, 1]], dtype=int32)

In [39]:
arr2

array([[1, 1, 1],
       [2, 1, 2],
       [1, 2, 1]], dtype=int32)

In [40]:
arr1-arr2

array([[ 1,  1,  1],
       [ 0,  1, -1],
       [ 1,  0,  0]], dtype=int32)

In [41]:
arr1 * arr2

array([[2, 2, 2],
       [4, 2, 2],
       [2, 4, 1]], dtype=int32)

In [42]:
arr1 > arr2

array([[ True,  True,  True],
       [False,  True, False],
       [ True, False, False]])

In [43]:
arr1

array([[2, 2, 2],
       [2, 2, 1],
       [2, 2, 1]], dtype=int32)

In [44]:
# operation on numpy string array
d=np.array(["pw","skills"])

In [45]:
d

array(['pw', 'skills'], dtype='<U6')

In [48]:
np.char.capitalize(d)

array(['Pw', 'Skills'], dtype='<U6')

In [46]:
np.char.upper(d)

array(['PW', 'SKILLS'], dtype='<U6')

In [49]:
# mathematical function
arr1

array([[2, 2, 2],
       [2, 2, 1],
       [2, 2, 1]], dtype=int32)

In [50]:
np.sin(arr1)

array([[0.90929743, 0.90929743, 0.90929743],
       [0.90929743, 0.90929743, 0.84147098],
       [0.90929743, 0.90929743, 0.84147098]])

In [51]:
np.cos(arr1)

array([[-0.41614684, -0.41614684, -0.41614684],
       [-0.41614684, -0.41614684,  0.54030231],
       [-0.41614684, -0.41614684,  0.54030231]])

In [52]:
np.tan(arr1)

array([[-2.18503986, -2.18503986, -2.18503986],
       [-2.18503986, -2.18503986,  1.55740772],
       [-2.18503986, -2.18503986,  1.55740772]])

In [53]:
np.log10(arr1)

array([[0.30103, 0.30103, 0.30103],
       [0.30103, 0.30103, 0.     ],
       [0.30103, 0.30103, 0.     ]])

In [54]:
np.exp(arr1)

array([[7.3890561 , 7.3890561 , 7.3890561 ],
       [7.3890561 , 7.3890561 , 2.71828183],
       [7.3890561 , 7.3890561 , 2.71828183]])

In [55]:
np.power(arr1,3)

array([[8, 8, 8],
       [8, 8, 1],
       [8, 8, 1]], dtype=int32)

In [56]:
arr1

array([[2, 2, 2],
       [2, 2, 1],
       [2, 2, 1]], dtype=int32)

In [57]:
np.max(arr1)

np.int32(2)

In [58]:
np.mean(arr1)

np.float64(1.7777777777777777)

In [59]:
np.min(arr1)

np.int32(1)

In [60]:
np.std(arr1)

np.float64(0.41573970964154905)

In [61]:
np.mean(arr1)

np.float64(1.7777777777777777)

In [62]:
np.var(arr1)

np.float64(0.1728395061728395)

In [63]:
arr1-arr2

array([[ 1,  1,  1],
       [ 0,  1, -1],
       [ 1,  0,  0]], dtype=int32)

In [64]:
np.subtract(arr1,arr2)

array([[ 1,  1,  1],
       [ 0,  1, -1],
       [ 1,  0,  0]], dtype=int32)

In [65]:
arr1*arr2

array([[2, 2, 2],
       [4, 2, 2],
       [2, 4, 1]], dtype=int32)

In [66]:
np.multiply(arr1,arr2)

array([[2, 2, 2],
       [4, 2, 2],
       [2, 4, 1]], dtype=int32)

In [67]:
np.mod(arr1,arr2) # return element wise remainder

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 0]], dtype=int32)

In [68]:
np.sqrt(arr1)

array([[1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.        ],
       [1.41421356, 1.41421356, 1.        ]])

In [69]:
# sorting and searching in numpy array
e=np.array([5,6,1,2])

In [70]:
e

array([5, 6, 1, 2])

In [ ]:
np.sort(e) # return a sorted copy of an array

array([1, 2, 5, 6])

In [72]:
f=np.array([5,199,200,6,7,8])

In [73]:
np.sort(f)

array([  5,   6,   7,   8, 199, 200])

In [74]:
np.searchsorted(f,170) # Find indices where element should be inserted to maintain order.

np.int64(6)

In [75]:
f=np.array([5,199,200,0,0,0,0,6,7,8])

In [76]:
f

array([  5, 199, 200,   0,   0,   0,   0,   6,   7,   8])

In [78]:
np.count_nonzero(f)

np.int64(6)

In [80]:
f[f>0]

array([  5, 199, 200,   6,   7,   8])

In [81]:
np.where(f>0) # same as above condition

(array([0, 1, 2, 7, 8, 9]),)

In [ ]:
np.extract(f>0,f) # same as above condition

array([  5, 199, 200,   6,   7,   8])

In [83]:
f

array([  5, 199, 200,   0,   0,   0,   0,   6,   7,   8])

In [84]:
f.byteswap() # swap the bytes of the array elements.

array([  360287970189639680, -4107282860161892352, -4035225266123964416,
                          0,                    0,                    0,
                          0,   432345564227567616,   504403158265495552,
         576460752303423488])

In [85]:
import numpy.matlib as nm
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [87]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# numpy Linear algebra (optional)

In [88]:
arr1

array([[2, 2, 2],
       [2, 2, 1],
       [2, 2, 1]], dtype=int32)

In [89]:
arr2

array([[1, 1, 1],
       [2, 1, 2],
       [1, 2, 1]], dtype=int32)

In [90]:
arr1@arr2

array([[8, 8, 8],
       [7, 6, 7],
       [7, 6, 7]], dtype=int32)

In [91]:
arr1

array([[2, 2, 2],
       [2, 2, 1],
       [2, 2, 1]], dtype=int32)

In [92]:
np.linalg.det(arr1)

np.float64(0.0)

In [93]:
np.linalg.det(arr2)

np.float64(0.0)

In [ ]:
# in matrix you can divide by another ,matrx,you have inverse.
np.linalg.inv(arr1)

In [96]:
a=np.array([[7,5.3,-3],[3,-5,2],[5,2,-7]])

In [97]:
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  2. , -7. ]])

In [98]:
b=np.array([16,8,0])

In [99]:
np.linalg.solve(a,b)

array([2.58342005, 0.77696844, 2.06729102])