In [1]:
import numpy as np

In [2]:
a=np.zeros(5) # Returns a new array of given shape and type,filled with zeros.

In [3]:
a.ndim

1

In [4]:
a

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
b=np.zeros((3,4))

In [8]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
b.ndim

2

In [14]:
c=np.ones(5)

In [15]:
c

array([1., 1., 1., 1., 1.])

In [16]:
c.ndim


1

In [20]:
n=np.zeros((10,4))

In [21]:
n


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
n.ndim

2

In [24]:
e=np.ones((10,4,2))

In [25]:
e

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [26]:
np.ones(5,dtype=int) # Returns a new array of given shape and type,filled with ones

array([1, 1, 1, 1, 1])

In [27]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
np.array([[2,2,2],[2,2,2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [29]:
# 3 dimensional array
np.zeros(1)

array([0.])

In [30]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
b=np.zeros((1,1,3,3))

In [32]:
b

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [33]:
b.ndim

4

In [34]:
arr=np.zeros((1,1,3,3))

In [39]:
a=arr+5

In [40]:
a

array([[[[5., 5., 5.],
         [5., 5., 5.],
         [5., 5., 5.]]]])

In [36]:
arr.ndim

4

In [41]:
a*2

array([[[[10., 10., 10.],
         [10., 10., 10.],
         [10., 10., 10.]]]])

In [43]:
arr1=np.zeros((1,1,3,3))

In [44]:
arr1

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [48]:
a=arr1+5

In [51]:
a*2

array([[[[10., 10., 10.],
         [10., 10., 10.],
         [10., 10., 10.]]]])

In [53]:
arr2=np.zeros((1,1,3,3))

In [54]:
arr2

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [57]:
b=arr2+4

In [58]:
b

array([[[[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]]]])

In [59]:
a*b

array([[[[16., 16., 16.],
         [16., 16., 16.],
         [16., 16., 16.]]]])

In [61]:
np.eye(3) # Returns a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [65]:
np.empty((3,4)) # Returns a new array of given shape and type,without initializing entities.it means entities in the array can be anything random values.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [66]:
np.empty((5,6))

array([[1.16998101e-311, 1.16998418e-311, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 5.02034658e+175],
       [1.92015071e-052, 1.88626265e+185, 9.13445745e+169,
        3.79991580e+175, 4.22288074e-062, 4.75730009e-038],
       [3.83819517e+151, 2.59903818e-144, 1.04918562e-153,
        7.69165785e+218, 5.04621343e+180, 1.04917822e-153],
       [9.08366793e+223, 1.92015071e-052, 1.88626265e+185,
        9.13445745e+169, 3.79991580e+175, 1.04915146e-153],
       [1.94918966e-153, 9.72160709e-072, 2.26334708e-076,
        7.27130349e-043, 2.59027896e-144, 7.79952704e-143]])

In [68]:
# optional >> random module
import random
random.choice((1,2,3,4,5))

5

In [69]:
random.choice("NIKHIL YADAV")

'V'

In [70]:
random.choice("nikhil yadav")

'i'

In [71]:
random.randrange(1,10)

4

In [ ]:
random.random() # random number generated between 0(include) and 1(exclude)

0.3941080520373139

In [73]:
lis=[1,2,3,4,5,6]
lis

[1, 2, 3, 4, 5, 6]

In [74]:
random.shuffle(lis)

In [75]:
lis

[1, 6, 5, 4, 3, 2]

In [76]:
random.uniform(7,14)

7.668223074593318

In [77]:
# random number related concept in numpy
np.array([])

array([], dtype=float64)

In [78]:
np.random.random_sample()

0.10533706408988575

In [ ]:
np.random.random_sample((5,)) # one dimensional array of 5 random nos

array([0.88447196, 0.60078218, 0.11943258, 0.99580867, 0.14047783])

In [83]:
np.random.rand((1))

array([0.96068837])

In [85]:
np.random.rand(2,3)

array([[0.29248505, 0.53371426, 0.70944485],
       [0.9526163 , 0.59956716, 0.59605491]])

In [ ]:
np.random.randn() # return a sample (or samples) from the "standard normal" distribution

0.7297944954969454

In [ ]:
np.random.randint(1,5,size=(3,4)) # start from 1 and end at 5-1 and give array of shape 3,4

array([[1, 4, 2, 3],
       [4, 2, 2, 3],
       [3, 4, 2, 4]], dtype=int32)

In [89]:
arr=np.random.randint(1,5,size=(3,4))

In [90]:
arr.ndim

2

In [91]:
arr.shape

(3, 4)

In [92]:
arr.size

12

In [93]:
arr

array([[4, 3, 3, 3],
       [4, 1, 4, 3],
       [4, 2, 1, 2]], dtype=int32)

In [98]:
# reshaping of array
arr3=arr.reshape(2,6) # Returns an array containing the same data with a new shape.

In [99]:
arr3

array([[4, 3, 3, 3, 4, 1],
       [4, 3, 4, 2, 1, 2]], dtype=int32)

In [100]:
arr3.size

12

In [101]:
arr3.shape

(2, 6)

In [102]:
arr3.ndim

2

In [ ]:
# Array size will never change,always reshape parameter should be multiplication of original array size.

In [103]:
arr3

array([[4, 3, 3, 3, 4, 1],
       [4, 3, 4, 2, 1, 2]], dtype=int32)

In [104]:
arr.reshape(3,2)

ValueError: cannot reshape array of size 12 into shape (3,2)

In [105]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [106]:
arr.reshape(3,4)

array([[4, 3, 3, 3],
       [4, 1, 4, 3],
       [4, 2, 1, 2]], dtype=int32)

In [107]:
arr.reshape(4,3)

array([[4, 3, 3],
       [3, 4, 1],
       [4, 3, 4],
       [2, 1, 2]], dtype=int32)

In [108]:
arr.reshape(1,12)

array([[4, 3, 3, 3, 4, 1, 4, 3, 4, 2, 1, 2]], dtype=int32)

In [110]:
arr.reshape(1,12)

array([[4, 3, 3, 3, 4, 1, 4, 3, 4, 2, 1, 2]], dtype=int32)

In [111]:
arr.reshape(12,1)

array([[4],
       [3],
       [3],
       [3],
       [4],
       [1],
       [4],
       [3],
       [4],
       [2],
       [1],
       [2]], dtype=int32)

In [112]:
# case when you don't know in reshape what should be the row or column count.
# use any negative value for rows or columns.
arr.reshape(4,-1)

array([[4, 3, 3],
       [3, 4, 1],
       [4, 3, 4],
       [2, 1, 2]], dtype=int32)

In [113]:
arr.reshape(-1,4)

array([[4, 3, 3, 3],
       [4, 1, 4, 3],
       [4, 2, 1, 2]], dtype=int32)

In [ ]:
arr.reshape(12,1).base # to see the original array

array([[4, 3, 3, 3],
       [4, 1, 4, 3],
       [4, 2, 1, 2]], dtype=int32)

In [ ]:
arr.reshape(2,2,3) # multiplication should be equals to arr size

array([[[4, 3, 3],
        [3, 4, 1]],

       [[4, 3, 4],
        [2, 1, 2]]], dtype=int32)

In [116]:
arr.reshape(1,2,2,3)

array([[[[4, 3, 3],
         [3, 4, 1]],

        [[4, 3, 4],
         [2, 1, 2]]]], dtype=int32)

In [117]:
arr.reshape(1,2,2,3).ndim

4

In [ ]:
arr.reshape(4,3,1) # 3 rows 1 column repeated 4 times in the third dimensional.

array([[[4],
        [3],
        [3]],

       [[3],
        [4],
        [1]],

       [[4],
        [3],
        [4]],

       [[2],
        [1],
        [2]]], dtype=int32)

In [119]:
# Conditions on array
arr1=np.random.randint(1,10,(5,6))

In [120]:
arr1

array([[7, 3, 3, 6, 9, 7],
       [7, 2, 3, 1, 3, 2],
       [6, 1, 1, 4, 6, 7],
       [9, 3, 8, 4, 2, 7],
       [6, 5, 6, 5, 8, 4]], dtype=int32)

In [121]:
arr1.shape

(5, 6)

In [122]:
arr1.size

30

In [123]:
arr1.ndim

2

In [ ]:
arr1[arr1>3] # Select all the element of arr1 where the condition is true

array([7, 6, 9, 7, 7, 6, 4, 6, 7, 9, 8, 4, 7, 6, 5, 6, 5, 8, 4],
      dtype=int32)

In [ ]:
# to access element in an array

In [126]:
arr1[0]

array([7, 3, 3, 6, 9, 7], dtype=int32)

In [127]:
arr1[1]

array([7, 2, 3, 1, 3, 2], dtype=int32)

In [128]:
arr1[1][2]

np.int32(3)

In [129]:
# fro oth row to 2nd row
arr1[0:3]

array([[7, 3, 3, 6, 9, 7],
       [7, 2, 3, 1, 3, 2],
       [6, 1, 1, 4, 6, 7]], dtype=int32)

In [130]:
# 0 to 2nd row and oth and 2nd column
arr1[0:3,[0,2]]

array([[7, 3],
       [7, 3],
       [6, 1]], dtype=int32)

In [131]:
# slicing on both rows and columns together
arr1

array([[7, 3, 3, 6, 9, 7],
       [7, 2, 3, 1, 3, 2],
       [6, 1, 1, 4, 6, 7],
       [9, 3, 8, 4, 2, 7],
       [6, 5, 6, 5, 8, 4]], dtype=int32)

In [132]:
arr1[0:3,1:3]

array([[3, 3],
       [2, 3],
       [1, 1]], dtype=int32)

In [133]:
arr1[0:3,[0,1]]

array([[7, 3],
       [7, 2],
       [6, 1]], dtype=int32)

In [134]:
arr1[0]

array([7, 3, 3, 6, 9, 7], dtype=int32)

In [136]:
arr1[0,[1,3]]

array([3, 6], dtype=int32)

In [137]:
arr1[2:4,[0,3]]

array([[6, 4],
       [9, 4]], dtype=int32)

In [ ]:
# Mathematical operation on two arrays
arr1=np.random.randint(1,2,(3,3))
arr2=np.random.randint(1,2,(3,3))

In [139]:
arr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [ ]:
arr2=np.random.randint(1,2,(3,3))

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [142]:
arr2

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [ ]:
arr1+arr2 # indexwise element addition

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

In [143]:
arr1-arr2

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

In [144]:
arr1=np.random.randint(1,2,(3,3))
arr2=np.random.randint(1,2,(3,3))

In [145]:
arr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [146]:
arr2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [147]:
arr1+arr2

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]], dtype=int32)

In [148]:
arr1-arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [ ]:
arr1*arr2 # index wise multiplication

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [150]:
arr1/arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [151]:
arr1=np.random.randint(1,2,(3,3))
arr2=np.random.randint(1,2,(3,3))

In [152]:
arr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [153]:
arr2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [154]:
arr1/0

C:\Users\91921\AppData\Local\Temp\ipykernel_13368\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
# matrix multiplication >> matrix is a specialised 2-d array
# matrix multiplication is different from index wise multiplication

In [155]:
arr1 @ arr2

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]], dtype=int32)

In [156]:
np.dot(arr1,arr2) # another way of matrix multiplication

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]], dtype=int32)

In [ ]:
# brutecasting

In [158]:
arr=np.zeros((3,4))

In [159]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [160]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [161]:
arr-5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [162]:
a=np.array([1,2,3,4])

In [163]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [164]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [165]:
a

array([1, 2, 3, 4])

In [ ]:
# Transpose >> converting rows to columns to rows

In [166]:
a.T

array([1, 2, 3, 4])