In [ ]:
# Numpy>> numerical python
# Developed in 2005 by travis aliphant
# before 2005 there were special mathematical tools(similar to Tara.Lingo)


In [9]:
import numpy as np # as is alias

In [10]:
np.__version__

'2.3.4'

In [11]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [12]:
lis=[1,2,3,"pwskills",3+5j,True,1.2] # list stored hetrogeneous data
type(lis)

list

In [ ]:
# Numpy stored the data in a numpy array
# An array is a container/data structures used to store data of same data types >> homogeneous data


In [ ]:
# why numpy? already we have list,C is one of the fastest programming language after c++.
# numpy is built using c >> Numpy computation is fast.
# due to array >> since it stores only homogeneous data,numpy array is faster.
# since it stores homogeneous data >> contiguous/continuous memory location.
# Mathematical computation is fast.

In [ ]:
l=[1,2,3,4,5] # numpy array is homogeneous >> all element can be integer,float,string.
arr=np.array(l) # numpy.ndarray>>n dimensional array
print(arr)

[1 2 3 4 5]


In [17]:
type(arr)

numpy.ndarray

In [20]:
arr

array([1, 2, 3, 4, 5])

In [19]:
l=[1,2,3,4,5,"Ajay"]
np.array(l)

array(['1', '2', '3', '4', '5', 'Ajay'], dtype='<U21')

In [21]:
l=[1,2,3,4,5,2.5]
np.array(l)

array([1. , 2. , 3. , 4. , 5. , 2.5])

In [22]:
arr=[1,2,3,4,5,2.5,"Nikhil"]
np.array(arr)

array(['1', '2', '3', '4', '5', '2.5', 'Nikhil'], dtype='<U32')

In [23]:
type(arr)

list

In [ ]:
arr.ndir # dir has only rows

In [ ]:
arr1=np.array([1,2,3],[4,5,6])
print(arr1)

In [27]:
mat=np.matrix([1,2,3,4]) # matrix is a specialised array of 2 dimensions.
type(mat)

numpy.matrix

In [28]:
mat.ndim

2

In [29]:
mat

matrix([[1, 2, 3, 4]])

In [30]:
# To understand the dimension ,see the opening/closing square bracket
np.matrix([[[1,2],[1,5],[3,6]]]) # will throw error-matrix must be 2-dimensional.


ValueError: matrix must be 2-dimensional

In [31]:
# more ways to array
l=[1,2,3]
np.array(l) # initial function as array to convert to an array,np.array come after this

array([1, 2, 3])

In [33]:
np.asanyarray([1,2,3])

array([1, 2, 3])

In [ ]:
# as any array will convert the input to an ndarray,but pass ndarray subclass throws
# if something is already an array or part of array,it will simply allow to pass through it.

In [34]:
np.asanyarray([1,2,3])

array([1, 2, 3])

In [35]:
mat

matrix([[1, 2, 3, 4]])

In [36]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [37]:
t=([1,2,3],[4,5,6])
type(t)

tuple

In [38]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
arr

[1, 2, 3, 4, 5, 2.5, 'Nikhil']

In [40]:
# accessing element of the array
arr[0]

1

In [41]:
# array is mutable 
arr[0]=1000

In [42]:
arr

[1000, 2, 3, 4, 5, 2.5, 'Nikhil']

In [44]:
a=arr # a and arr will point to some memory location,so if there is change is a or arr.
# it will reflect can both
print(a)

[1000, 2, 3, 4, 5, 2.5, 'Nikhil']


In [ ]:
# shallow copy >> change in one array will lead to change in another.

In [45]:
a[0]=5000

In [46]:
arr

[5000, 2, 3, 4, 5, 2.5, 'Nikhil']

In [ ]:
b=arr.copy() # deep copy >> change in one array will not reflect in another

In [48]:
b

[5000, 2, 3, 4, 5, 2.5, 'Nikhil']

In [49]:
b[0]

5000

In [50]:
b[0]=11000

In [51]:
b

[11000, 2, 3, 4, 5, 2.5, 'Nikhil']

In [ ]:
# To create an array>> np.array,np.asarray,np.asany array

In [ ]:
# multiple approches to generate any array

In [53]:
np.fromfunction(lambda i,j:i==j,(3,3)) # Construct an array by executing a function over each coordination

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [54]:
1==2

False

In [58]:
arr1.ndin

NameError: name 'arr1' is not defined

In [56]:
arr1.shape # shape of array

NameError: name 'arr1' is not defined

In [ ]:
arr1.size # no of student in array

In [59]:
# True is stored as 1 and false 0 in python
True-False

1

In [70]:
arr2=np.fromfunction(lambda i,j:i*j,(3,3))
print(arr2)


[[0. 0. 0.]
 [0. 1. 2.]
 [0. 2. 4.]]


In [71]:
arr2


array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [72]:
arr2.ndim

2

In [73]:
arr2.shape

(3, 3)

In [74]:
arr2.size

9

In [75]:
for i in range(5):
    print(i)

0
1
2
3
4


In [76]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [77]:
iterator=(i for i in range(5))

In [78]:
np.fromiter(iterator,int)

array([0, 1, 2, 3, 4])

In [79]:
np.fromstring('22 23 24',sep="")

ValueError: The binary mode of fromstring is removed, use frombuffer instead

In [80]:
# for string character you have to use split
string="Ajay,Bijay,Sanjay"
string.split(",")

['Ajay', 'Bijay', 'Sanjay']

In [81]:
np.array(string.split(","))

array(['Ajay', 'Bijay', 'Sanjay'], dtype='<U6')

In [82]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# another method of numpy >> to generate a sequence of number
np.arange(1,10) # arrange returns evenly specified values within a given interval

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
np.arange(1,10,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [87]:
np.linspace(1,5,10) # give me 10 numbers between 1 to 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])